<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>39306bd2-14a2-44e3-a55f-a2cb0947b1dd</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TypingUsers.db" />
    <None Remove="TypingUsers.db-shm" />
    <None Remove="TypingUsers.db-wal" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorClient\TypingBlazor.Client.csproj" />
    <ProjectReference Include="..\shared\shared.csproj" />
    <ProjectReference Include="..\TypingLogic\TypingLogic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\bootstrap\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />

  </ItemGroup>

</Project>
